SET client_encoding = 'UNICODE';
BEGIN;

CREATE TABLE international_country (
    id serial NOT NULL PRIMARY KEY,
    name character varying(255),
    iso_code2 character(2),
    iso_code3 character(3),
    eu_status boolean,
    currency_code character(3)
);

CREATE TABLE international_currency (
    id serial NOT NULL PRIMARY KEY,
    code character(3),
    name character varying(255) DEFAULT ''::character varying NOT NULL,
    symbol_left character varying(255),
    symbol_right character varying(255)
);

CREATE TABLE international_currency_rate (
    id serial NOT NULL PRIMARY KEY,
    currency_code character(3),
    currency_code_from character(3),
    source character varying(255),
    date timestamp(0) without time zone,
    amount numeric(12,8)
);


INSERT INTO international_country VALUES (1, 'Afghanistan', 'AF', 'AFG', false, NULL);
INSERT INTO international_country VALUES (2, 'Albania', 'AL', 'ALB', false, NULL);
INSERT INTO international_country VALUES (3, 'Algeria', 'DZ', 'DZA', false, NULL);
INSERT INTO international_country VALUES (4, 'American Samoa', 'AS', 'ASM', false, NULL);
INSERT INTO international_country VALUES (5, 'Andorra', 'AD', 'AND', false, NULL);
INSERT INTO international_country VALUES (6, 'Angola', 'AO', 'AGO', false, NULL);
INSERT INTO international_country VALUES (7, 'Anguilla', 'AI', 'AIA', false, NULL);
INSERT INTO international_country VALUES (8, 'Antarctica', 'AQ', 'ATA', false, NULL);
INSERT INTO international_country VALUES (9, 'Antigua and Barbuda', 'AG', 'ATG', false, NULL);
INSERT INTO international_country VALUES (10, 'Argentina', 'AR', 'ARG', false, NULL);
INSERT INTO international_country VALUES (11, 'Armenia', 'AM', 'ARM', false, NULL);
INSERT INTO international_country VALUES (12, 'Aruba', 'AW', 'ABW', false, NULL);
INSERT INTO international_country VALUES (13, 'Australia', 'AU', 'AUS', false, NULL);
INSERT INTO international_country VALUES (14, 'Austria', 'AT', 'AUT', true, NULL);
INSERT INTO international_country VALUES (15, 'Azerbaijan', 'AZ', 'AZE', false, NULL);
INSERT INTO international_country VALUES (16, 'Bahamas', 'BS', 'BHS', false, NULL);
INSERT INTO international_country VALUES (17, 'Bahrain', 'BH', 'BHR', false, NULL);
INSERT INTO international_country VALUES (18, 'Bangladesh', 'BD', 'BGD', false, NULL);
INSERT INTO international_country VALUES (19, 'Barbados', 'BB', 'BRB', false, NULL);
INSERT INTO international_country VALUES (20, 'Belarus', 'BY', 'BLR', false, NULL);
INSERT INTO international_country VALUES (21, 'Belgium', 'BE', 'BEL', true, NULL);
INSERT INTO international_country VALUES (22, 'Belize', 'BZ', 'BLZ', false, NULL);
INSERT INTO international_country VALUES (23, 'Benin', 'BJ', 'BEN', false, NULL);
INSERT INTO international_country VALUES (24, 'Bermuda', 'BM', 'BMU', false, NULL);
INSERT INTO international_country VALUES (25, 'Bhutan', 'BT', 'BTN', false, NULL);
INSERT INTO international_country VALUES (26, 'Bolivia', 'BO', 'BOL', false, NULL);
INSERT INTO international_country VALUES (27, 'Bosnia and Herzegowina', 'BA', 'BIH', false, NULL);
INSERT INTO international_country VALUES (28, 'Botswana', 'BW', 'BWA', false, NULL);
INSERT INTO international_country VALUES (29, 'Bouvet Island', 'BV', 'BVT', false, NULL);
INSERT INTO international_country VALUES (30, 'Brazil', 'BR', 'BRA', false, NULL);
INSERT INTO international_country VALUES (31, 'British Indian Ocean Territory', 'IO', 'IOT', false, NULL);
INSERT INTO international_country VALUES (32, 'Brunei Darussalam', 'BN', 'BRN', false, NULL);
INSERT INTO international_country VALUES (33, 'Bulgaria', 'BG', 'BGR', false, NULL);
INSERT INTO international_country VALUES (34, 'Burkina Faso', 'BF', 'BFA', false, NULL);
INSERT INTO international_country VALUES (35, 'Burundi', 'BI', 'BDI', false, NULL);
INSERT INTO international_country VALUES (36, 'Cambodia', 'KH', 'KHM', false, NULL);
INSERT INTO international_country VALUES (37, 'Cameroon', 'CM', 'CMR', false, NULL);
INSERT INTO international_country VALUES (38, 'Canada', 'CA', 'CAN', false, NULL);
INSERT INTO international_country VALUES (39, 'Cape Verde', 'CV', 'CPV', false, NULL);
INSERT INTO international_country VALUES (40, 'Cayman Islands', 'KY', 'CYM', false, NULL);
INSERT INTO international_country VALUES (41, 'Central African Republic', 'CF', 'CAF', false, NULL);
INSERT INTO international_country VALUES (42, 'Chad', 'TD', 'TCD', false, NULL);
INSERT INTO international_country VALUES (43, 'Chile', 'CL', 'CHL', false, NULL);
INSERT INTO international_country VALUES (44, 'China', 'CN', 'CHN', false, NULL);
INSERT INTO international_country VALUES (45, 'Christmas Island', 'CX', 'CXR', false, NULL);
INSERT INTO international_country VALUES (46, 'Cocos (Keeling) Islands', 'CC', 'CCK', false, NULL);
INSERT INTO international_country VALUES (47, 'Colombia', 'CO', 'COL', false, NULL);
INSERT INTO international_country VALUES (48, 'Comoros', 'KM', 'COM', false, NULL);
INSERT INTO international_country VALUES (49, 'Congo', 'CG', 'COG', false, NULL);
INSERT INTO international_country VALUES (50, 'Cook Islands', 'CK', 'COK', false, NULL);
INSERT INTO international_country VALUES (51, 'Costa Rica', 'CR', 'CRI', false, NULL);
INSERT INTO international_country VALUES (52, 'Cote D''Ivoire', 'CI', 'CIV', false, NULL);
INSERT INTO international_country VALUES (53, 'Croatia', 'HR', 'HRV', false, NULL);
INSERT INTO international_country VALUES (54, 'Cuba', 'CU', 'CUB', false, NULL);
INSERT INTO international_country VALUES (55, 'Cyprus', 'CY', 'CYP', true, NULL);
INSERT INTO international_country VALUES (56, 'Czech Republic', 'CZ', 'CZE', true, NULL);
INSERT INTO international_country VALUES (57, 'Denmark', 'DK', 'DNK', true, NULL);
INSERT INTO international_country VALUES (58, 'Djibouti', 'DJ', 'DJI', false, NULL);
INSERT INTO international_country VALUES (59, 'Dominica', 'DM', 'DMA', false, NULL);
INSERT INTO international_country VALUES (60, 'Dominican Republic', 'DO', 'DOM', false, NULL);
INSERT INTO international_country VALUES (61, 'East Timor', 'TP', 'TMP', false, NULL);
INSERT INTO international_country VALUES (62, 'Ecuador', 'EC', 'ECU', false, NULL);
INSERT INTO international_country VALUES (63, 'Egypt', 'EG', 'EGY', false, NULL);
INSERT INTO international_country VALUES (64, 'El Salvador', 'SV', 'SLV', false, NULL);
INSERT INTO international_country VALUES (65, 'Equatorial Guinea', 'GQ', 'GNQ', false, NULL);
INSERT INTO international_country VALUES (66, 'Eritrea', 'ER', 'ERI', false, NULL);
INSERT INTO international_country VALUES (67, 'Estonia', 'EE', 'EST', true, NULL);
INSERT INTO international_country VALUES (68, 'Ethiopia', 'ET', 'ETH', false, NULL);
INSERT INTO international_country VALUES (69, 'Falkland Islands (Malvinas)', 'FK', 'FLK', false, NULL);
INSERT INTO international_country VALUES (70, 'Faroe Islands', 'FO', 'FRO', false, NULL);
INSERT INTO international_country VALUES (71, 'Fiji', 'FJ', 'FJI', false, NULL);
INSERT INTO international_country VALUES (72, 'Finland', 'FI', 'FIN', true, NULL);
INSERT INTO international_country VALUES (73, 'France', 'FR', 'FRA', true, NULL);
INSERT INTO international_country VALUES (74, 'Madeira', 'ME', 'MDR', false, NULL);
INSERT INTO international_country VALUES (75, 'French Guiana', 'GF', 'GUF', false, NULL);
INSERT INTO international_country VALUES (76, 'French Polynesia', 'PF', 'PYF', false, NULL);
INSERT INTO international_country VALUES (77, 'French Southern Territories', 'TF', 'ATF', false, NULL);
INSERT INTO international_country VALUES (78, 'Gabon', 'GA', 'GAB', false, NULL);
INSERT INTO international_country VALUES (79, 'Gambia', 'GM', 'GMB', false, NULL);
INSERT INTO international_country VALUES (80, 'Georgia', 'GE', 'GEO', false, NULL);
INSERT INTO international_country VALUES (81, 'Germany', 'DE', 'DEU', true, NULL);
INSERT INTO international_country VALUES (82, 'Ghana', 'GH', 'GHA', false, NULL);
INSERT INTO international_country VALUES (83, 'Gibraltar', 'GI', 'GIB', false, NULL);
INSERT INTO international_country VALUES (84, 'Greece', 'GR', 'GRC', true, NULL);
INSERT INTO international_country VALUES (85, 'Greenland', 'GL', 'GRL', false, NULL);
INSERT INTO international_country VALUES (86, 'Grenada', 'GD', 'GRD', false, NULL);
INSERT INTO international_country VALUES (87, 'Guadeloupe', 'GP', 'GLP', false, NULL);
INSERT INTO international_country VALUES (88, 'Guam', 'GU', 'GUM', false, NULL);
INSERT INTO international_country VALUES (89, 'Guatemala', 'GT', 'GTM', false, NULL);
INSERT INTO international_country VALUES (90, 'Guinea', 'GN', 'GIN', false, NULL);
INSERT INTO international_country VALUES (91, 'Guinea-bissau', 'GW', 'GNB', false, NULL);
INSERT INTO international_country VALUES (92, 'Guyana', 'GY', 'GUY', false, NULL);
INSERT INTO international_country VALUES (93, 'Haiti', 'HT', 'HTI', false, NULL);
INSERT INTO international_country VALUES (94, 'Heard and Mc Donald Islands', 'HM', 'HMD', false, NULL);
INSERT INTO international_country VALUES (95, 'Honduras', 'HN', 'HND', false, NULL);
INSERT INTO international_country VALUES (96, 'Hong Kong', 'HK', 'HKG', false, NULL);
INSERT INTO international_country VALUES (97, 'Hungary', 'HU', 'HUN', true, NULL);
INSERT INTO international_country VALUES (98, 'Iceland', 'IS', 'ISL', false, NULL);
INSERT INTO international_country VALUES (99, 'India', 'IN', 'IND', false, NULL);
INSERT INTO international_country VALUES (100, 'Indonesia', 'ID', 'IDN', false, NULL);
INSERT INTO international_country VALUES (101, 'Iran (Islamic Republic of)', 'IR', 'IRN', false, NULL);
INSERT INTO international_country VALUES (102, 'Iraq', 'IQ', 'IRQ', false, NULL);
INSERT INTO international_country VALUES (103, 'Ireland', 'IE', 'IRL', true, NULL);
INSERT INTO international_country VALUES (104, 'Israel', 'IL', 'ISR', false, NULL);
INSERT INTO international_country VALUES (105, 'Italy', 'IT', 'ITA', true, NULL);
INSERT INTO international_country VALUES (106, 'Jamaica', 'JM', 'JAM', false, NULL);
INSERT INTO international_country VALUES (107, 'Japan', 'JP', 'JPN', false, NULL);
INSERT INTO international_country VALUES (108, 'Jordan', 'JO', 'JOR', false, NULL);
INSERT INTO international_country VALUES (109, 'Kazakhstan', 'KZ', 'KAZ', false, NULL);
INSERT INTO international_country VALUES (110, 'Kenya', 'KE', 'KEN', false, NULL);
INSERT INTO international_country VALUES (111, 'Kiribati', 'KI', 'KIR', false, NULL);
INSERT INTO international_country VALUES (112, 'Korea, Democratic People''s Republic of', 'KP', 'PRK', false, NULL);
INSERT INTO international_country VALUES (113, 'Korea, Republic of', 'KR', 'KOR', false, NULL);
INSERT INTO international_country VALUES (114, 'Kuwait', 'KW', 'KWT', false, NULL);
INSERT INTO international_country VALUES (115, 'Kyrgyzstan', 'KG', 'KGZ', false, NULL);
INSERT INTO international_country VALUES (116, 'Lao People''s Democratic Republic', 'LA', 'LAO', false, NULL);
INSERT INTO international_country VALUES (117, 'Latvia', 'LV', 'LVA', true, NULL);
INSERT INTO international_country VALUES (118, 'Lebanon', 'LB', 'LBN', false, NULL);
INSERT INTO international_country VALUES (119, 'Lesotho', 'LS', 'LSO', false, NULL);
INSERT INTO international_country VALUES (120, 'Liberia', 'LR', 'LBR', false, NULL);
INSERT INTO international_country VALUES (121, 'Libyan Arab Jamahiriya', 'LY', 'LBY', false, NULL);
INSERT INTO international_country VALUES (122, 'Liechtenstein', 'LI', 'LIE', false, NULL);
INSERT INTO international_country VALUES (123, 'Lithuania', 'LT', 'LTU', true, NULL);
INSERT INTO international_country VALUES (124, 'Luxembourg', 'LU', 'LUX', true, NULL);
INSERT INTO international_country VALUES (125, 'Macau', 'MO', 'MAC', false, NULL);
INSERT INTO international_country VALUES (126, 'Macedonia', 'MK', 'MKD', false, NULL);
INSERT INTO international_country VALUES (127, 'Madagascar', 'MG', 'MDG', false, NULL);
INSERT INTO international_country VALUES (128, 'Malawi', 'MW', 'MWI', false, NULL);
INSERT INTO international_country VALUES (129, 'Malaysia', 'MY', 'MYS', false, NULL);
INSERT INTO international_country VALUES (130, 'Maldives', 'MV', 'MDV', false, NULL);
INSERT INTO international_country VALUES (131, 'Mali', 'ML', 'MLI', false, NULL);
INSERT INTO international_country VALUES (132, 'Malta', 'MT', 'MLT', true, NULL);
INSERT INTO international_country VALUES (133, 'Marshall Islands', 'MH', 'MHL', false, NULL);
INSERT INTO international_country VALUES (134, 'Martinique', 'MQ', 'MTQ', false, NULL);
INSERT INTO international_country VALUES (135, 'Mauritania', 'MR', 'MRT', false, NULL);
INSERT INTO international_country VALUES (136, 'Mauritius', 'MU', 'MUS', false, NULL);
INSERT INTO international_country VALUES (137, 'Mayotte', 'YT', 'MYT', false, NULL);
INSERT INTO international_country VALUES (138, 'Mexico', 'MX', 'MEX', false, NULL);
INSERT INTO international_country VALUES (139, 'Micronesia', 'FM', 'FSM', false, NULL);
INSERT INTO international_country VALUES (140, 'Moldova', 'MD', 'MDA', false, NULL);
INSERT INTO international_country VALUES (141, 'Monaco', 'MC', 'MCO', false, NULL);
INSERT INTO international_country VALUES (142, 'Mongolia', 'MN', 'MNG', false, NULL);
INSERT INTO international_country VALUES (143, 'Montserrat', 'MS', 'MSR', false, NULL);
INSERT INTO international_country VALUES (144, 'Morocco', 'MA', 'MAR', false, NULL);
INSERT INTO international_country VALUES (145, 'Mozambique', 'MZ', 'MOZ', false, NULL);
INSERT INTO international_country VALUES (146, 'Myanmar', 'MM', 'MMR', false, NULL);
INSERT INTO international_country VALUES (147, 'Namibia', 'NA', 'NAM', false, NULL);
INSERT INTO international_country VALUES (148, 'Nauru', 'NR', 'NRU', false, NULL);
INSERT INTO international_country VALUES (149, 'Nepal', 'NP', 'NPL', false, NULL);
INSERT INTO international_country VALUES (150, 'Netherlands', 'NL', 'NLD', true, NULL);
INSERT INTO international_country VALUES (151, 'Netherlands Antilles', 'AN', 'ANT', false, NULL);
INSERT INTO international_country VALUES (152, 'New Caledonia', 'NC', 'NCL', false, NULL);
INSERT INTO international_country VALUES (153, 'New Zealand', 'NZ', 'NZL', false, NULL);
INSERT INTO international_country VALUES (154, 'Nicaragua', 'NI', 'NIC', false, NULL);
INSERT INTO international_country VALUES (155, 'Niger', 'NE', 'NER', false, NULL);
INSERT INTO international_country VALUES (156, 'Nigeria', 'NG', 'NGA', false, NULL);
INSERT INTO international_country VALUES (157, 'Niue', 'NU', 'NIU', false, NULL);
INSERT INTO international_country VALUES (158, 'Norfolk Island', 'NF', 'NFK', false, NULL);
INSERT INTO international_country VALUES (159, 'Northern Mariana Islands', 'MP', 'MNP', false, NULL);
INSERT INTO international_country VALUES (160, 'Norway', 'NO', 'NOR', false, NULL);
INSERT INTO international_country VALUES (161, 'Oman', 'OM', 'OMN', false, NULL);
INSERT INTO international_country VALUES (162, 'Pakistan', 'PK', 'PAK', false, NULL);
INSERT INTO international_country VALUES (163, 'Palau', 'PW', 'PLW', false, NULL);
INSERT INTO international_country VALUES (164, 'Panama', 'PA', 'PAN', false, NULL);
INSERT INTO international_country VALUES (165, 'Papua New Guinea', 'PG', 'PNG', false, NULL);
INSERT INTO international_country VALUES (166, 'Paraguay', 'PY', 'PRY', false, NULL);
INSERT INTO international_country VALUES (167, 'Peru', 'PE', 'PER', false, NULL);
INSERT INTO international_country VALUES (168, 'Philippines', 'PH', 'PHL', false, NULL);
INSERT INTO international_country VALUES (169, 'Pitcairn', 'PN', 'PCN', false, NULL);
INSERT INTO international_country VALUES (170, 'Poland', 'PL', 'POL', true, NULL);
INSERT INTO international_country VALUES (171, 'Portugal', 'PT', 'PRT', true, NULL);
INSERT INTO international_country VALUES (172, 'Puerto Rico', 'PR', 'PRI', false, NULL);
INSERT INTO international_country VALUES (173, 'Qatar', 'QA', 'QAT', false, NULL);
INSERT INTO international_country VALUES (174, 'Reunion', 'RE', 'REU', false, NULL);
INSERT INTO international_country VALUES (175, 'Romania', 'RO', 'ROM', false, NULL);
INSERT INTO international_country VALUES (176, 'Russia', 'RU', 'RUS', false, NULL);
INSERT INTO international_country VALUES (177, 'Rwanda', 'RW', 'RWA', false, NULL);
INSERT INTO international_country VALUES (178, 'Saint Kitts and Nevis', 'KN', 'KNA', false, NULL);
INSERT INTO international_country VALUES (179, 'Saint Lucia', 'LC', 'LCA', false, NULL);
INSERT INTO international_country VALUES (180, 'Saint Vincent and the Grenadines', 'VC', 'VCT', false, NULL);
INSERT INTO international_country VALUES (181, 'Samoa', 'WS', 'WSM', false, NULL);
INSERT INTO international_country VALUES (182, 'San Marino', 'SM', 'SMR', false, NULL);
INSERT INTO international_country VALUES (183, 'Sao Tome and Principe', 'ST', 'STP', false, NULL);
INSERT INTO international_country VALUES (184, 'Saudi Arabia', 'SA', 'SAU', false, NULL);
INSERT INTO international_country VALUES (185, 'Senegal', 'SN', 'SEN', false, NULL);
INSERT INTO international_country VALUES (186, 'Seychelles', 'SC', 'SYC', false, NULL);
INSERT INTO international_country VALUES (187, 'Sierra Leone', 'SL', 'SLE', false, NULL);
INSERT INTO international_country VALUES (188, 'Singapore', 'SG', 'SGP', false, NULL);
INSERT INTO international_country VALUES (189, 'Slovakia (Slovak Republic)', 'SK', 'SVK', true, NULL);
INSERT INTO international_country VALUES (190, 'Slovenia', 'SI', 'SVN', true, NULL);
INSERT INTO international_country VALUES (191, 'Solomon Islands', 'SB', 'SLB', false, NULL);
INSERT INTO international_country VALUES (192, 'Somalia', 'SO', 'SOM', false, NULL);
INSERT INTO international_country VALUES (193, 'South Africa', 'ZA', 'ZAF', false, NULL);
INSERT INTO international_country VALUES (194, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', false, NULL);
INSERT INTO international_country VALUES (195, 'Spain', 'ES', 'ESP', true, NULL);
INSERT INTO international_country VALUES (196, 'Sri Lanka', 'LK', 'LKA', false, NULL);
INSERT INTO international_country VALUES (197, 'St. Helena', 'SH', 'SHN', false, NULL);
INSERT INTO international_country VALUES (198, 'St. Pierre and Miquelon', 'PM', 'SPM', false, NULL);
INSERT INTO international_country VALUES (199, 'Sudan', 'SD', 'SDN', false, NULL);
INSERT INTO international_country VALUES (200, 'Suriname', 'SR', 'SUR', false, NULL);
INSERT INTO international_country VALUES (201, 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM', false, NULL);
INSERT INTO international_country VALUES (202, 'Swaziland', 'SZ', 'SWZ', false, NULL);
INSERT INTO international_country VALUES (203, 'Sweden', 'SE', 'SWE', true, NULL);
INSERT INTO international_country VALUES (204, 'Switzerland', 'CH', 'CHE', false, NULL);
INSERT INTO international_country VALUES (205, 'Syrian Arab Republic', 'SY', 'SYR', false, NULL);
INSERT INTO international_country VALUES (206, 'Taiwan', 'TW', 'TWN', false, NULL);
INSERT INTO international_country VALUES (207, 'Tajikistan', 'TJ', 'TJK', false, NULL);
INSERT INTO international_country VALUES (208, 'Tanzania, United Republic of', 'TZ', 'TZA', false, NULL);
INSERT INTO international_country VALUES (209, 'Thailand', 'TH', 'THA', false, NULL);
INSERT INTO international_country VALUES (210, 'Togo', 'TG', 'TGO', false, NULL);
INSERT INTO international_country VALUES (211, 'Tokelau', 'TK', 'TKL', false, NULL);
INSERT INTO international_country VALUES (212, 'Tonga', 'TO', 'TON', false, NULL);
INSERT INTO international_country VALUES (213, 'Trinidad and Tobago', 'TT', 'TTO', false, NULL);
INSERT INTO international_country VALUES (214, 'Tunisia', 'TN', 'TUN', false, NULL);
INSERT INTO international_country VALUES (215, 'Turkey', 'TR', 'TUR', false, NULL);
INSERT INTO international_country VALUES (216, 'Turkmenistan', 'TM', 'TKM', false, NULL);
INSERT INTO international_country VALUES (217, 'Turks and Caicos Islands', 'TC', 'TCA', false, NULL);
INSERT INTO international_country VALUES (218, 'Tuvalu', 'TV', 'TUV', false, NULL);
INSERT INTO international_country VALUES (219, 'Uganda', 'UG', 'UGA', false, NULL);
INSERT INTO international_country VALUES (220, 'Ukraine', 'UA', 'UKR', false, NULL);
INSERT INTO international_country VALUES (221, 'United Arab Emirates', 'AE', 'ARE', false, NULL);
INSERT INTO international_country VALUES (222, 'United Kingdom', 'GB', 'GBR', true, NULL);
INSERT INTO international_country VALUES (223, 'United States', 'US', 'USA', false, NULL);
INSERT INTO international_country VALUES (224, 'United States Minor Outlying Islands', 'UM', 'UMI', false, NULL);
INSERT INTO international_country VALUES (225, 'Uruguay', 'UY', 'URY', false, NULL);
INSERT INTO international_country VALUES (226, 'Uzbekistan', 'UZ', 'UZB', false, NULL);
INSERT INTO international_country VALUES (227, 'Vanuatu', 'VU', 'VUT', false, NULL);
INSERT INTO international_country VALUES (228, 'Vatican City State (Holy See)', 'VA', 'VAT', false, NULL);
INSERT INTO international_country VALUES (229, 'Venezuela', 'VE', 'VEN', false, NULL);
INSERT INTO international_country VALUES (230, 'Viet Nam', 'VN', 'VNM', false, NULL);
INSERT INTO international_country VALUES (231, 'Virgin Islands (British)', 'VG', 'VGB', false, NULL);
INSERT INTO international_country VALUES (232, 'Virgin Islands (U.S.)', 'VI', 'VIR', false, NULL);
INSERT INTO international_country VALUES (233, 'Wallis and Futuna Islands', 'WF', 'WLF', false, NULL);
INSERT INTO international_country VALUES (234, 'Western Sahara', 'EH', 'ESH', false, NULL);
INSERT INTO international_country VALUES (235, 'Yemen', 'YE', 'YEM', false, NULL);
INSERT INTO international_country VALUES (236, 'Yugoslavia', 'YU', 'YUG', false, NULL);
INSERT INTO international_country VALUES (237, 'Zaire', 'ZR', 'ZAR', false, NULL);
INSERT INTO international_country VALUES (238, 'Zambia', 'ZM', 'ZMB', false, NULL);
INSERT INTO international_country VALUES (239, 'Zimbabwe', 'ZW', 'ZWE', false, NULL);


INSERT INTO international_currency VALUES (1, 'EUR', 'Euro', '&euro;', NULL);
INSERT INTO international_currency VALUES (2, 'GBP', 'British Pound', '&pound;', NULL);
INSERT INTO international_currency VALUES (3, 'AFA', 'Afghanistan Afghani', '', NULL);
INSERT INTO international_currency VALUES (4, 'ALL', 'Albanian Lek', '', NULL);
INSERT INTO international_currency VALUES (5, 'DZD', 'Algerian Dinar', '', NULL);
INSERT INTO international_currency VALUES (6, 'ADF', 'Andorran Franc', '', NULL);
INSERT INTO international_currency VALUES (7, 'AON', 'Angolan New Kwanza', '', NULL);
INSERT INTO international_currency VALUES (8, 'ARS', 'Argentine Peso', '', NULL);
INSERT INTO international_currency VALUES (9, 'AMD', 'Armenian Dram', '', NULL);
INSERT INTO international_currency VALUES (10, 'AWG', 'Aruban Florin', '', NULL);
INSERT INTO international_currency VALUES (11, 'AUD', 'Australian Dollar', '', NULL);
INSERT INTO international_currency VALUES (12, 'AZM', 'Azerbaijan Manat', '', NULL);
INSERT INTO international_currency VALUES (13, 'BSD', 'Bahamanian Dollar', '', NULL);
INSERT INTO international_currency VALUES (14, 'BHD', 'Bahraini Dinar', '', NULL);
INSERT INTO international_currency VALUES (15, 'BDT', 'Bangladeshi Taka', '', NULL);
INSERT INTO international_currency VALUES (16, 'BBD', 'Barbados Dollar', '', NULL);
INSERT INTO international_currency VALUES (17, 'BYR', 'Belarus Ruble', '', NULL);
INSERT INTO international_currency VALUES (18, 'BZD', 'Belize Dollar', '', NULL);
INSERT INTO international_currency VALUES (19, 'BMD', 'Bermudian Dollar', '', NULL);
INSERT INTO international_currency VALUES (20, 'BTN', 'Bhutan Ngultrum', '', NULL);
INSERT INTO international_currency VALUES (21, 'BOB', 'Bolivian Boliviano', '', NULL);
INSERT INTO international_currency VALUES (22, 'BAM', 'Bosnia and Herzegovina Marka', '', NULL);
INSERT INTO international_currency VALUES (23, 'BWP', 'Botswana Pula', '', NULL);
INSERT INTO international_currency VALUES (24, 'BRL', 'Brazilian Real', '', NULL);
INSERT INTO international_currency VALUES (25, 'BND', 'Brunei Dollar', '', NULL);
INSERT INTO international_currency VALUES (26, 'BGL', 'Bulgarian Lev', '', NULL);
INSERT INTO international_currency VALUES (27, 'BIF', 'Burundi Franc', '', NULL);
INSERT INTO international_currency VALUES (28, 'KHR', 'Cambodian Riel', '', NULL);
INSERT INTO international_currency VALUES (29, 'CAD', 'Canadian Dollar', '', NULL);
INSERT INTO international_currency VALUES (30, 'BPS', 'Canton & Enderbury Island Pound', '', NULL);
INSERT INTO international_currency VALUES (31, 'CVE', 'Cape Verde Escudo', '', NULL);
INSERT INTO international_currency VALUES (32, 'KYD', 'Cayman Islands Dollar', '', NULL);
INSERT INTO international_currency VALUES (33, 'CFP', 'Central Pacific Franc', '', NULL);
INSERT INTO international_currency VALUES (34, 'XOF', 'CFA Franc BCEAO', '', NULL);
INSERT INTO international_currency VALUES (35, 'XAF', 'CFA Franc BEAC', '', NULL);
INSERT INTO international_currency VALUES (36, 'CLP', 'Chilean Peso', '', NULL);
INSERT INTO international_currency VALUES (37, 'CLF', 'Chilean U. Fomento', '', NULL);
INSERT INTO international_currency VALUES (38, 'CNY', 'Chinese Yuan Renminbi', '', NULL);
INSERT INTO international_currency VALUES (39, 'COP', 'Colombian Peso', '', NULL);
INSERT INTO international_currency VALUES (40, 'KMF', 'Comoros Franc', '', NULL);
INSERT INTO international_currency VALUES (41, 'CRC', 'Costa Rican Colon', '', NULL);
INSERT INTO international_currency VALUES (42, 'HRK', 'Croatian Kuna', '', NULL);
INSERT INTO international_currency VALUES (43, 'CUP', 'Cuban Peso', '', NULL);
INSERT INTO international_currency VALUES (44, 'CYP', 'Cyprus Pound', '', NULL);
INSERT INTO international_currency VALUES (46, 'DKK', 'Danish Krone', '', NULL);
INSERT INTO international_currency VALUES (47, 'DJF', 'Djibouti Franc', '', NULL);
INSERT INTO international_currency VALUES (48, 'DOP', 'Dominican R. Peso', '', NULL);
INSERT INTO international_currency VALUES (49, 'XCD', 'East Caribbean Dollar', '', NULL);
INSERT INTO international_currency VALUES (50, 'ECS', 'Ecuador Sucre', '', NULL);
INSERT INTO international_currency VALUES (51, 'EGP', 'Egyptian Pound', '', NULL);
INSERT INTO international_currency VALUES (52, 'SVC', 'El Salvador Colon', '', NULL);
INSERT INTO international_currency VALUES (53, 'ERN', 'Eritrea Nakfa', '', NULL);
INSERT INTO international_currency VALUES (54, 'EEK', 'Estonian Kroon', '', NULL);
INSERT INTO international_currency VALUES (55, 'ETB', 'Ethiopian Birr', '', NULL);
INSERT INTO international_currency VALUES (56, 'FKP', 'Falkland Islands Pound', '', NULL);
INSERT INTO international_currency VALUES (57, 'FJD', 'Fiji Dollar', '', NULL);
INSERT INTO international_currency VALUES (58, 'XPF', 'French Pacific Islands Franc', '', NULL);
INSERT INTO international_currency VALUES (59, 'GMD', 'Gambian Dalasi', '', NULL);
INSERT INTO international_currency VALUES (60, 'GEL', 'Georgian Lari', '', NULL);
INSERT INTO international_currency VALUES (61, 'GHC', 'Ghanaian Cedi', '', NULL);
INSERT INTO international_currency VALUES (62, 'GIP', 'Gibraltar Pound', '', NULL);
INSERT INTO international_currency VALUES (64, 'GTQ', 'Guatemalan Quetzal', '', NULL);
INSERT INTO international_currency VALUES (65, 'GGP', 'Guernsey Pound', '', NULL);
INSERT INTO international_currency VALUES (66, 'GNF', 'Guinea Franc', '', NULL);
INSERT INTO international_currency VALUES (67, 'GYD', 'Guyanese Dollar', '', NULL);
INSERT INTO international_currency VALUES (68, 'HTG', 'Haitian Gourde', '', NULL);
INSERT INTO international_currency VALUES (69, 'HNL', 'Honduran Lempira', '', NULL);
INSERT INTO international_currency VALUES (70, 'HKD', 'Hong Kong Dollar', '', NULL);
INSERT INTO international_currency VALUES (71, 'HUF', 'Hungarian Forint', '', NULL);
INSERT INTO international_currency VALUES (72, 'ISK', 'Iceland Krona', '', NULL);
INSERT INTO international_currency VALUES (73, 'INR', 'Indian Rupee', '', NULL);
INSERT INTO international_currency VALUES (74, 'IDR', 'Indonesian Rupiah', '', NULL);
INSERT INTO international_currency VALUES (75, 'IRR', 'Iranian Rial', '', NULL);
INSERT INTO international_currency VALUES (76, 'IQD', 'Iraqi Dinar', '', NULL);
INSERT INTO international_currency VALUES (77, 'IMP', 'Isle Of Man Pound', '', NULL);
INSERT INTO international_currency VALUES (78, 'ILS', 'Israeli New Shekel', '', NULL);
INSERT INTO international_currency VALUES (79, 'JMD', 'Jamaican Dollar', '', NULL);
INSERT INTO international_currency VALUES (80, 'JPY', 'Japanese Yen', '', NULL);
INSERT INTO international_currency VALUES (81, 'JEP', 'Jersey Pound', '', NULL);
INSERT INTO international_currency VALUES (82, 'JOD', 'Jordanian Dinar', '', NULL);
INSERT INTO international_currency VALUES (83, 'KZT', 'Kazakhstan Tenge', '', NULL);
INSERT INTO international_currency VALUES (84, 'KES', 'Kenyan Shilling', '', NULL);
INSERT INTO international_currency VALUES (85, 'KWD', 'Kuwaiti Dinar', '', NULL);
INSERT INTO international_currency VALUES (86, 'KGS', 'Kyrgyzstan Som', '', NULL);
INSERT INTO international_currency VALUES (87, 'LAK', 'Lao Kip', '', NULL);
INSERT INTO international_currency VALUES (88, 'LVL', 'Latvian Lats', '', NULL);
INSERT INTO international_currency VALUES (89, 'LBP', 'Lebanese Pound', '', NULL);
INSERT INTO international_currency VALUES (90, 'LSL', 'Lesotho Loti', '', NULL);
INSERT INTO international_currency VALUES (91, 'LRD', 'Liberian Dollar', '', NULL);
INSERT INTO international_currency VALUES (92, 'LYD', 'Libyan Dinar', '', NULL);
INSERT INTO international_currency VALUES (93, 'LTL', 'Lithuanian Litas', '', NULL);
INSERT INTO international_currency VALUES (94, 'MOP', 'Macau Pataca', '', NULL);
INSERT INTO international_currency VALUES (95, 'MKD', 'Macedonia Denar', '', NULL);
INSERT INTO international_currency VALUES (96, 'MGF', 'Malagasy Franc', '', NULL);
INSERT INTO international_currency VALUES (97, 'MWK', 'Malawi Kwacha', '', NULL);
INSERT INTO international_currency VALUES (98, 'MYR', 'Malaysian Ringgit', '', NULL);
INSERT INTO international_currency VALUES (99, 'MVR', 'Maldive Rufiyaa', '', NULL);
INSERT INTO international_currency VALUES (100, 'MTL', 'Maltese Lira', '', NULL);
INSERT INTO international_currency VALUES (101, 'MRO', 'Mauritanian Ouguiya', '', NULL);
INSERT INTO international_currency VALUES (102, 'MUR', 'Mauritius Rupee', '', NULL);
INSERT INTO international_currency VALUES (103, 'MXP', 'Mexican Peso', '', NULL);
INSERT INTO international_currency VALUES (104, 'UDI', 'Mexican Unidades De Inversion', '', NULL);
INSERT INTO international_currency VALUES (105, 'MDL', 'Moldova Leu', '', NULL);
INSERT INTO international_currency VALUES (106, 'MNT', 'Mongolian Tugrik', '', NULL);
INSERT INTO international_currency VALUES (107, 'MAD', 'Moroccan Dirham', '', NULL);
INSERT INTO international_currency VALUES (108, 'MZM', 'Mozambique Metical', '', NULL);
INSERT INTO international_currency VALUES (109, 'MMK', 'Myanmar Kyat', '', NULL);
INSERT INTO international_currency VALUES (110, 'NAD', 'Namibia Dollar', '', NULL);
INSERT INTO international_currency VALUES (111, 'NPR', 'Nepalese Rupee', '', NULL);
INSERT INTO international_currency VALUES (112, 'NZD', 'New Zealand Dollar', '', NULL);
INSERT INTO international_currency VALUES (113, 'NIO', 'Nicaraguan Cordoba Oro', '', NULL);
INSERT INTO international_currency VALUES (114, 'NGN', 'Nigerian Naira', '', NULL);
INSERT INTO international_currency VALUES (115, 'ANG', 'NL Antillian Guilder', '', NULL);
INSERT INTO international_currency VALUES (116, 'KPW', 'North Korean Won', '', NULL);
INSERT INTO international_currency VALUES (117, 'NOK', 'Norwegian Kroner', '', NULL);
INSERT INTO international_currency VALUES (118, 'OMR', 'Omani Rial', '', NULL);
INSERT INTO international_currency VALUES (119, 'PKR', 'Pakistan Rupee', '', NULL);
INSERT INTO international_currency VALUES (120, 'XPD', 'Palladium', '', NULL);
INSERT INTO international_currency VALUES (121, 'PAB', 'Panamanian Balboa', '', NULL);
INSERT INTO international_currency VALUES (122, 'PGK', 'Papua New Guinea Kina', '', NULL);
INSERT INTO international_currency VALUES (123, 'PYG', 'Paraguay Guarani', '', NULL);
INSERT INTO international_currency VALUES (124, 'PEN', 'Peruvian Nuevo Sol', '', NULL);
INSERT INTO international_currency VALUES (125, 'PHP', 'Philippine Peso', '', NULL);
INSERT INTO international_currency VALUES (126, 'XPT', 'Platinum', '', NULL);
INSERT INTO international_currency VALUES (127, 'PLN', 'Polish New Zloty', '', NULL);
INSERT INTO international_currency VALUES (128, 'QAR', 'Qatari Rial', '', NULL);
INSERT INTO international_currency VALUES (129, 'CDF', 'Republic of Congo Franc', '', NULL);
INSERT INTO international_currency VALUES (130, 'ROL', 'Romanian Leu', '', NULL);
INSERT INTO international_currency VALUES (131, 'RUB', 'Russian Rouble', '', NULL);
INSERT INTO international_currency VALUES (132, 'RWF', 'Rwanda Franc', '', NULL);
INSERT INTO international_currency VALUES (133, 'WST', 'Samoan Tala', '', NULL);
INSERT INTO international_currency VALUES (134, 'STD', 'Sao Tome/Principe Dobra', '', NULL);
INSERT INTO international_currency VALUES (135, 'SAR', 'Saudi Riyal', '', NULL);
INSERT INTO international_currency VALUES (136, 'SPL', 'Seborga Luigini', '', NULL);
INSERT INTO international_currency VALUES (137, 'SCR', 'Seychelles Rupee', '', NULL);
INSERT INTO international_currency VALUES (138, 'SLL', 'Sierra Leone Leone', '', NULL);
INSERT INTO international_currency VALUES (139, 'XAG', 'Silver', '', NULL);
INSERT INTO international_currency VALUES (140, 'SGD', 'Singapore Dollar', '', NULL);
INSERT INTO international_currency VALUES (141, 'SKK', 'Slovak Koruna', '', NULL);
INSERT INTO international_currency VALUES (142, 'SIT', 'Slovenian Tolar', '', NULL);
INSERT INTO international_currency VALUES (143, 'SBD', 'Solomon Islands Dollar', '', NULL);
INSERT INTO international_currency VALUES (144, 'SOS', 'Somali Shilling', '', NULL);
INSERT INTO international_currency VALUES (145, 'ZAR', 'South African Rand', '', NULL);
INSERT INTO international_currency VALUES (146, 'KRW', 'South Korean Won', '', NULL);
INSERT INTO international_currency VALUES (147, 'XDR', 'Special Drawing Right', '', NULL);
INSERT INTO international_currency VALUES (148, 'LKR', 'Sri Lanka Rupee', '', NULL);
INSERT INTO international_currency VALUES (149, 'SHP', 'St. Helena Pound', '', NULL);
INSERT INTO international_currency VALUES (150, 'SDD', 'Sudanese Dinar', '', NULL);
INSERT INTO international_currency VALUES (151, 'SDP', 'Sudanese Pound', '', NULL);
INSERT INTO international_currency VALUES (152, 'SRG', 'Suriname Guilder', '', NULL);
INSERT INTO international_currency VALUES (153, 'SZL', 'Swaziland Lilangeni', '', NULL);
INSERT INTO international_currency VALUES (154, 'SEK', 'Swedish Krona', '', NULL);
INSERT INTO international_currency VALUES (155, 'CHF', 'Swiss Franc', '', NULL);
INSERT INTO international_currency VALUES (156, 'SYP', 'Syrian Pound', '', NULL);
INSERT INTO international_currency VALUES (157, 'TWD', 'Taiwan Dollar', '', NULL);
INSERT INTO international_currency VALUES (158, 'TJS', 'Tajikistan Ruble', '', NULL);
INSERT INTO international_currency VALUES (159, 'TZS', 'Tanzanian Shilling', '', NULL);
INSERT INTO international_currency VALUES (160, 'THB', 'Thai Baht', '', NULL);
INSERT INTO international_currency VALUES (161, 'TOP', 'Tonga Paanga', '', NULL);
INSERT INTO international_currency VALUES (162, 'TTD', 'Trinidad/Tobago Dollar', '', NULL);
INSERT INTO international_currency VALUES (163, 'TND', 'Tunisian Dinar', '', NULL);
INSERT INTO international_currency VALUES (164, 'TRY', 'Turkish New Lira', '', NULL);
INSERT INTO international_currency VALUES (165, 'TMM', 'Turkmenistan Manat', '', NULL);
INSERT INTO international_currency VALUES (166, 'UGS', 'Uganda Shilling', '', NULL);
INSERT INTO international_currency VALUES (167, 'UAH', 'Ukraine Hryvnia', '', NULL);
INSERT INTO international_currency VALUES (168, 'UYP', 'Uruguayan Peso', '', NULL);
INSERT INTO international_currency VALUES (179, '_RB', 'Rabbits', '', 'Rabbits');
INSERT INTO international_currency VALUES (170, 'AED', 'Utd. Arab Emir. Dirham', '', NULL);
INSERT INTO international_currency VALUES (171, 'UZS', 'Uzbekistan Sum', '', NULL);
INSERT INTO international_currency VALUES (172, 'VUV', 'Vanuatu Vatu', '', NULL);
INSERT INTO international_currency VALUES (173, 'VEB', 'Venezuelan Bolivar', '', NULL);
INSERT INTO international_currency VALUES (174, 'VND', 'Vietnamese Dong', '', NULL);
INSERT INTO international_currency VALUES (175, 'YER', 'Yemeni Rial', '', NULL);
INSERT INTO international_currency VALUES (176, 'YUN', 'Yugoslav Dinar', '', NULL);
INSERT INTO international_currency VALUES (177, 'ZMK', 'Zambian Kwacha', '', NULL);
INSERT INTO international_currency VALUES (178, 'ZWD', 'Zimbabwe Dollar', '', NULL);
INSERT INTO international_currency VALUES (45, 'CZK', 'Czech Koruna', '', 'Kč');
INSERT INTO international_currency VALUES (169, 'USD', 'US Dollar', '$', NULL);
INSERT INTO international_currency VALUES (63, 'XAU', 'Gold', '', 'g.&nbsp;of&nbsp;Gold');


--
-- Data for TOC entry 90 (OID 18112)
-- Name: international_currency_rate; Type: TABLE DATA; Schema: public; Owner: liquidlight
--

INSERT INTO international_currency_rate (currency_code, currency_code_from, source, date, amount) VALUES ('USD', 'GBP', 'google', '2011-03-24', 1.6228);
INSERT INTO international_currency_rate (currency_code, currency_code_from, source, date, amount) VALUES ('EUR', 'GBP', 'google', '2011-03-24', 1.15075876);
INSERT INTO international_currency_rate (currency_code, currency_code_from, source, date, amount) VALUES ('CZK', 'GBP', 'google', '2011-03-24', 28.0741817);
INSERT INTO international_currency_rate (currency_code, currency_code_from, source, date, amount) VALUES ('AUD', 'GBP', 'google', '2011-03-24', 1.59976341);
INSERT INTO international_currency_rate (currency_code, currency_code_from, source, date, amount) VALUES ('JPY', 'GBP', 'google', '2011-03-24', 131.315747);
INSERT INTO international_currency_rate (currency_code, currency_code_from, source, date, amount) VALUES ('CAD', 'GBP', 'google', '2011-03-24', 1.58791354);
INSERT INTO international_currency_rate (currency_code, currency_code_from, source, date, amount) VALUES ('HKD', 'GBP', 'google', '2011-03-24', 12.6500577);
INSERT INTO international_currency_rate (currency_code, currency_code_from, source, date, amount) VALUES ('NZD', 'GBP', 'google', '2011-03-24', 2.17504356);

SELECT pg_catalog.setval('international_country_id_seq', (SELECT max(id) FROM international_country), true);
SELECT pg_catalog.setval('international_currency_id_seq', (SELECT max(id) FROM international_currency), true);
SELECT pg_catalog.setval('international_currency_rate_id_seq', (SELECT max(id) FROM international_currency_rate), true);
COMMIT;
